services:
  jira_cycle_time_extractor:
    build:
      context: .
      dockerfile: ./docker/apps/jira_cycle_time_extractor/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./docker/apps/data:/app/data
    environment:
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_PASSWORD=${JIRA_PASSWORD}
      - OUTPUT_PATH=/app/data/jira_metrics.csv
      - CUSTOM_JQL=${CUSTOM_JQL}
  reporting_app:
    build:
      context: .
      dockerfile: ./docker/apps/reporting_app/Dockerfile
    ports:
      - "8050:8050"
