services:
  jira_cycle_time_extractor:
    build:
      context: .
      dockerfile: ./docker/apps/jira_cycle_time_extractor/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/data:/app/data
  reporting_app:
    build:
      context: .
      dockerfile: ./docker/apps/reporting_app/Dockerfile
    ports:
      - "8050:8050"
