aws_region   = "ap-southeast-2"
vpc_id       = "vpc-c38d7fa5"
subnet_cidrs = ["172.31.7.0/24", "172.31.8.0/24"]
application_name = "jira-metrics"
cluster_name = "jira-metrics-cluster"
extractor_ecr_repository_name = "jira-metrics-extractor"
reporting_ecr_repository_name = "reporting-app"
environment  = "dev"
jira_username = "rey.rahadian@mecca.com.au"
jira_password = ""
custom_jql = "project in (LFW, MFW, DMA, COM, SIT, WEB) and updated >= -12w"