from src.reporting_app.config.constants import (
    STAGE_THRESHOLDS, PRIORITY_ORDER,
    THRESHOLD_STAGE_COLUMNS_DURATION_IN_DAYS,
    THRESHOLD_STAGE_COLUMNS_IN_SPRINT,
    ALL_STAGE_COLUMNS_DURATIONS_IN_DAYS,
    COLORS
)