Connection:
    Domain: https://mecca-brands.atlassian.net/
    #Open Jira in your browser and see the domain name in the browser link, ie. jira.microsoft.com or microsoft.atlassian.net
    Username: xxx
    #Use an email you use to access Jira. See https://jira.eurowag.com/secure/ViewProfile.jspa.
    Password: xxx
    # is your Jira API Token. The token can be generated at https://id.atlassian.com/manage-profile/security/api-tokens


JQL:
    #Query: project in ("LFW", "COM", "SIT") and updated >= -12w
    # Product Engineering
    Query: project in ("LFW","MFW","DMA", "COM", "SIT", "WEB") and updated >= -1d
    # Platform Engineering
    #Query: project in ("PAYAPI", "PLE", "RIS", "RS", "AD", "AMY", "CAP", "DEA", "ILA", "MAI", "MFS", "MNL", "SAP", "SHI", "SIC", "UML", "USA", "WAP", "WEX", "ZES") and updated >= -24w
    # Everyone
    #Query: project in ("LFW","MFW","DMA", "COM", "SIT", "WEB", "PAYAPI", "PLE", "RIS", "RS", "AD", "AMY", "CAP", "DEA", "ILA", "MAI", "MFS", "MNL", "SAP", "SHI", "SIC", "UML", "USA", "WAP", "WEX", "ZES") and updated >= -24w

# Map field names to additional attributes to extract
Attributes:
    Sprint: customfield_10020.name
    SprintGoals: customfield_10020.goal
    SprintStartDate: customfield_10020.startDate
    SprintEndDate: customfield_10020.endDate
    StoryPoints: customfield_10042
    Stage: status.name
    StatusCategory: status.statusCategory.name
    Priority: priority.name
    Labels: labels
    Components: components.name
    Version: fixVersions.last.name
    VersionRelease: fixVersions.last.releaseDate
    ParentId: parent.key
    ParentName: parent.fields.summary
    ParentType: parent.fields.issuetype.name
    AssigneeName: assignee.displayName
    #LinksToOutwardKey: issuelinks.first.outwardIssue.key
    #LinksToInwardKey: issuelinks.first.inwardIssue.key
    Timeoriginalestimate: timeoriginalestimate
    Timeestimate: timeestimate
    Timespent: timespent
    CreatedDate: created
    UpdatedDate: updated
    FixVersions: fixVersions.name
    Project: project.name
    Squad: customfield_11376.value
    #AggreagateTimeoriginalestimate: aggregatetimeoriginalestimate
    #AggreagateTimeestimate: aggregatetimeestimate
    #AggreagateTimespent: aggregatetimespent
    #Workratio: workratio
    #Environment: customfield_10081.last.value
    #HierarchyProductItemName: customfield_18701.fields.summary
    #HierarchyProductItemKey: customfield_18701.key
    #HierarchyEpicType: customfield_21401.value

